-- =====================
-- applications 테이블
-- =====================
create table applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  date text not null,
  gender text not null,
  name text not null,
  birth_year text not null,
  photo_url text,
  contact text not null,
  referral text not null,
  status text default 'pending' not null check (status in ('pending', 'confirmed', 'rejected'))
);

alter table applications enable row level security;

create policy "Anyone can insert applications"
  on applications for insert with check (true);

create policy "Anyone can select applications"
  on applications for select using (true);

create policy "Anyone can update applications"
  on applications for update using (true);

-- =====================
-- events 테이블 (신청 가능 날짜 관리)
-- =====================
create table events (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  date text not null unique,
  time text not null,
  female_seats int not null default 0,
  male_seats int not null default 0
);

alter table events enable row level security;

create policy "Anyone can read events"
  on events for select using (true);

create policy "Anyone can manage events"
  on events for all using (true);

-- =====================
-- party_settings 테이블 (파티 노출 여부)
-- =====================
create table party_settings (
  id bigint generated by default as identity primary key,
  party_type text unique not null check (party_type in ('introvert', 'wine')),
  is_visible boolean default true not null
);

alter table party_settings enable row level security;

create policy "Anyone can read party settings"
  on party_settings for select using (true);

create policy "Anyone can manage party settings"
  on party_settings for all using (true);

-- 초기 데이터
insert into party_settings (party_type, is_visible) values ('introvert', true), ('wine', true);

-- =====================
-- Storage: photos 버킷
-- =====================
-- Dashboard > Storage > New Bucket
-- Bucket name: photos
-- Public: ON (사진 URL 공개 접근용)
--
-- Storage 정책 (Dashboard > Storage > photos > Policies):
-- insert: (bucket_id = 'photos')  → allow all
-- select: (bucket_id = 'photos')  → allow all
