import type { Metadata } from "next";
import { Noto_Sans_KR } from 'next/font/google'
import "./globals.css";


const notoSans = Noto_Sans_KR({
  variable: '--font-noto-sans',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
      className={`${notoSans.variable} font-sans antialiased m-0 p-0`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
