import type { Metadata } from "next";
import { Nanum_Gothic} from 'next/font/google'
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import 'antd/dist/antd.css'

const nanumGothic = Nanum_Gothic({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
      className={`${nanumGothic.className} font-sans antialiased m-0 p-0`}
        suppressHydrationWarning={true}
      >
      <Header />
<main className="flex-1">
        {children}
        </main>
      <Footer />

      </body>
    </html>
  );
}
